### ISSUE TITLE
IMPORTANT - User Sync adds pending and banned accounts!

### ISSUE THREAD

**Issue by gmbhneo** [hizzle-co/noptin#72]
**Describe the bug**
If you sync your users to your subscribers all users get synchronized. Even Users who are shadow banned or not even activated!

**To Reproduce**
Just sync your users if you have multiple inactivated accounts. They will appear as subscribers and the suer count will also show a different number as your regular users.

**Expected behavior**
This REALLY should not happen.

**Screenshots**
https://ibb.co/7bV4zSH

**Comment by gmbhneo** [comment]
Anyone having the same issue? Is this plugin still maintained?

**Comment by picocodes** [comment]
Hi there @gmbhneo 

Sorry for the late response.

As far as I know, WordPress itself does not provide a way to ban users. That is why we sync all users. I assume that you are using an external plugin to ban users. Kindly provide me the name of the plugin and I'll fix the issue in Monday's release.

**Comment by gmbhneo** [comment]
Hey @picocodes 

Thanks for getting back to me. I am using a couple of plugins. But my best bet is "Buddypress". 

But as far is I know even bare bone Wordpress is sending activation emails before letting someone do something. These accounts (not activated ones) are getting synced too. At least in my case. So it should not be a plugin related issue.

Let me know if you need more information.

All the best

**Comment by picocodes** [comment]
Yeah, WordPress does indeed send out notifications to new users asking them to log in and change the password. However, it is impossible for other plugins to know if a user logged in to change their password or not.

Since you mentioned BuddyPress, I did a quick search and it seems like [BuddyPress saves unconfirmed users with a 'user_status=2' entry in the users' table](https://buddypress.trac.wordpress.org/ticket/8075). This will be quick to implement (a fix will be available in Monday's release).

As for the banned users, there are several BuddyPress addons that allow you to ban users so it might be hard to fix unless you can tell me the specific addon that lets you ban users.

**Comment by gmbhneo** [comment]
Oh great to hear. Well the only one I use which should so something like this is also Buddypress. It marks a user to be a "spammer" and should also give them a "user_status=2" at least as far as I know. So I think it will be fixed by just excluding them. 

I will give it a try after the next update and tell you if it works or not.

**Comment by picocodes** [comment]
Nice, [here is the commit](https://github.com/hizzle-co/noptin/commit/1a01f268c0f247b402863774fe587fda29192d41) containing the fix. It's scheduled to release on Monday.
