### ISSUE TITLE
Automated email campaign – emails sent out even when there are no new posts

### ISSUE THREAD

**Issue by friapro** [hizzle-co/noptin#792]
### Description

Since the new version that fixed [the error with the date not being displayed in post digest emails](https://github.com/hizzle-co/noptin/issues/770) (thanks for that, by the way!), digest emails are now sent out even when there are no new posts. It's just an empty email with the logo, links to unsubscribe, etc This happens daily. Previously, the daily email would only go out if there were new posts.

**Comment by picocodes** [comment]
Hi @friapro,

That should not happen. If you're using the [[posts]] merge tag instead of the [[post_digest]] merge tag, ensure you've set it to not send if there are no posts as shown below:-

`[[posts post_type="post" skiponempty=yes since_last_send=yes style=list]]`

If you're using the visual editor, there should be a checkbox to disable sending the email if there are no new posts. Please confirm that it is checked.

**Comment by picocodes** [comment]
Hi,

The checkbox only shows if you're using the visual editor and the "Posts" block. It does the same things as specifying skiponempty=yes in your merge tag.

The since_last_send=yes instructs the merge tag to only show posts published since the last send, hence why your preview shows no posts. You can remove the argument temporarily preview other posts and then re-add when you're ready to publish the campaign.

The next update will auto-remove this when previewing campaigns.

**Comment by pstimpel** [comment]
We are facing the same issue. We copied your email-posts-list.php file to the custom theme folder. This is running through an array of $campaign_posts in a foreach construct. How do I solve the issue in this situation?

**Comment by X-Raym** [comment]
@picocodes Hi ! Can you make a screensot so we can see where this checkbox is supposed to be ? I dont see it.

Can you confirm that 

```
[[post_digest style=list limit=40]]
```

isn't good enough anymore to not send empty emails ?

do I need it to change to this ?

```
[[posts post_type="post" skiponempty=yes since_last_send=yes style=list]]
```

Thx!

**Comment by pstimpel** [comment]
Seems, they do not respond to already closed tickets. I was trying to make the point that the given explanation does not work for me, but no answer yet.

**Comment by X-Raym** [comment]
@pstimpel yes I am not sure to understand @picocodes answer, as it mention a checbox only available in pro version of the plugin. As te free version used to be able to not send if no new posts, if would be a regression if it doesnt work this way anymore (at least, it is surprising that users are xpected to change the sortcode especiallly considering that seeing this error means that at least one newsletter has been sent to all users empty)

@picocodes as been pretty good support so far, it may be just a small delay.

**Comment by pstimpel** [comment]
@X-Raym : yep, patience is key. 

For reference, this was my issue, which was closed marked a dpulicate of this one here, but it not. 

[https://github.com/hizzle-co/noptin/issues/801](https://github.com/hizzle-co/noptin/issues/801)
