### ISSUE TITLE
IP insted of domain name

### ISSUE THREAD

**Issue by jissenkarate** [hizzle-co/noptin#945]
### Description

When sending out auto emails the link inside is a IP from my side and not the domain name

### Screenshots

![IP](https://github.com/user-attachments/assets/3d35dff8-c9fd-4f40-b652-1d6a3982549e)

**Comment by picocodes** [comment]
If WordPress is showing an IP address instead of a domain, it could be because WordPress has incorrect settings for the site's domain:
**Check the WordPress settings**
Log into WordPress, go to Settings > General, and change the WordPress Address and Site Address to the correct domain name.
**Edit the wp-config.php file**
Add the following lines to the file, changing example.com to the domain:
```php
define('WP_SITEURL', 'http://example.com');
define('WP_HOME', 'http://example.com'); 
```
