### ISSUE TITLE
Subscribers are unsubscribed without clicking an unsubscribe link

### ISSUE THREAD

**Issue by treehouse103** [hizzle-co/noptin#954]
### Description

I have several subscribers who have Gmail or corporate Google-hosted email accounts that keep having their subscription status set to unsubscribe, even though they never click on an unsubscribe link. Looking through the error logs, this happens at the same time as opening an email. Then some time later, they complain that they're no longer getting emails.

### Screenshots

![Screenshot 2024-12-02 at 5 22 17 PM](https://github.com/user-attachments/assets/d5fc26d1-8ae9-470e-930b-36f7b8fb4ff6)

**Comment by picocodes** [comment]
Hi @treehouse103,

Google might be prefetching the unsubscribe URLs hence unintentionally unsubscribing them.

Try creating a manual unsubscribe page and link to it instead of using the [[unsubscribe_url]] merge tag:- https://noptin.com/guide/subscription-forms/unsubscribe-forms/

We're also working on adding an extra button to the unsubscribe page instead of automatically unsubscribing the subscriber.

**Comment by picocodes** [comment]
Updated here:- https://github.com/hizzle-co/noptin/commit/cd7df1037da9f9cb9baab32fd910a7fd78982b39
